states = ["AK",
          "AZ",
          "CA",
          "CO",
          "HI",
          "ID",
          "MT",
          "NM",
          "NV",
          "OR",
          "UT",
          "WA",
          "WY"]

full_states = {"ak": "alaska",
               "az": "arizona",
               "ca": "california",
               "co": "colorado",
               "hi": "hawaii",
               "id": "idaho",
               "mt": "montana",
               "nm": "new mexico",
               "nv": "nevada",
               "or": "oregon",
               "ut": "utah",
               "wa": "washington",
               "wy": "wyoming"}

topics = ["Geography",
          "History",
          "Population",
          "Economy",
          "Culture",
          "Education",
          "Government"]
